[package]
name = "torin-0"
version = "0.1.0"
edition = "2021"

[dependencies]
torin = { git = "https://github.com/marc2332/freya/", branch = "fix/custom-sendanymap-for-torin", default-features = false }
